//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMSA.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an alphabet.
        /// </summary>
        public static string AddAlphabet {
            get {
                return ResourceManager.GetString("AddAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet name.
        /// </summary>
        public static string AlphabetName {
            get {
                return ResourceManager.GetString("AlphabetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabets.
        /// </summary>
        public static string Alphabets {
            get {
                return ResourceManager.GetString("Alphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII.
        /// </summary>
        public static string Ascii {
            get {
                return ResourceManager.GetString("Ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille alphabet.
        /// </summary>
        public static string BraillePageTitle {
            get {
                return ResourceManager.GetString("BraillePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string ColorConverterPageTitle {
            get {
                return ResourceManager.GetString("ColorConverterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to binary.
        /// </summary>
        public static string ConvertToBinary {
            get {
                return ResourceManager.GetString("ConvertToBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech (including diacritics).
        /// </summary>
        public static string CzechDiacritics {
            get {
                return ResourceManager.GetString("CzechDiacritics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption.
        /// </summary>
        public static string Decryption {
            get {
                return ResourceManager.GetString("Decryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alphabet.
        /// </summary>
        public static string EditAlphabetPageTitle {
            get {
                return ResourceManager.GetString("EditAlphabetPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English alphabet.
        /// </summary>
        public static string EnglishAlphabet {
            get {
                return ResourceManager.GetString("EnglishAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find primes up to.
        /// </summary>
        public static string FindPrimesUpTo {
            get {
                return ResourceManager.GetString("FindPrimesUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag semaphore.
        /// </summary>
        public static string FlagSemaphorePageTitle {
            get {
                return ResourceManager.GetString("FlagSemaphorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency analysis.
        /// </summary>
        public static string FrequencyAnalysisPageTitle {
            get {
                return ResourceManager.GetString("FrequencyAnalysisPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From radix.
        /// </summary>
        public static string FromRadix {
            get {
                return ResourceManager.GetString("FromRadix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek alphabet.
        /// </summary>
        public static string GreekAlphabet {
            get {
                return ResourceManager.GetString("GreekAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew alphabet.
        /// </summary>
        public static string HebrewAlphabet {
            get {
                return ResourceManager.GetString("HebrewAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters of the alphabet.
        /// </summary>
        public static string LettersOfTheAlphabet {
            get {
                return ResourceManager.GetString("LettersOfTheAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage alphabets.
        /// </summary>
        public static string ManageAlphabetsPageTitle {
            get {
                return ResourceManager.GetString("ManageAlphabetsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher App.
        /// </summary>
        public static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash is &quot;-&quot; dot is &quot;.&quot; and separator is &quot;/&quot;.
        /// </summary>
        public static string MorseEntryPlaceholder {
            get {
                return ResourceManager.GetString("MorseEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morse code.
        /// </summary>
        public static string MorsePageTitle {
            get {
                return ResourceManager.GetString("MorsePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New alphabet.
        /// </summary>
        public static string NewAlphabet {
            get {
                return ResourceManager.GetString("NewAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric base.
        /// </summary>
        public static string NumericBase {
            get {
                return ResourceManager.GetString("NumericBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number code.
        /// </summary>
        public static string NumericPageTitle {
            get {
                return ResourceManager.GetString("NumericPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers separated by comma.
        /// </summary>
        public static string NumersSeparatedByComma {
            get {
                return ResourceManager.GetString("NumersSeparatedByComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omitted letter.
        /// </summary>
        public static string OmittedLetter {
            get {
                return ResourceManager.GetString("OmittedLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playfair cipher.
        /// </summary>
        public static string PlayfairPageTitle {
            get {
                return ResourceManager.GetString("PlayfairPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime count: {0}.
        /// </summary>
        public static string PrimeCountFormat {
            get {
                return ResourceManager.GetString("PrimeCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primes.
        /// </summary>
        public static string PrimesPageTitle {
            get {
                return ResourceManager.GetString("PrimesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix.
        /// </summary>
        public static string Radix {
            get {
                return ResourceManager.GetString("Radix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix converter.
        /// </summary>
        public static string RadixConverterPageTitle {
            get {
                return ResourceManager.GetString("RadixConverterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian alphabet.
        /// </summary>
        public static string RussianAlphabet {
            get {
                return ResourceManager.GetString("RussianAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select alphabet.
        /// </summary>
        public static string SelectAlphabetPageTitle {
            get {
                return ResourceManager.GetString("SelectAlphabetPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        public static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To radix.
        /// </summary>
        public static string ToRadix {
            get {
                return ResourceManager.GetString("ToRadix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        public static string Unicode {
            get {
                return ResourceManager.GetString("Unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper bound.
        /// </summary>
        public static string UpperBound {
            get {
                return ResourceManager.GetString("UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet shift.
        /// </summary>
        public static string VigenerePageTitle {
            get {
                return ResourceManager.GetString("VigenerePageTitle", resourceCulture);
            }
        }
    }
}
